init:
    terraform init

plan:
    terraform plan

apply:
    terraform apply -auto-approve

destroy:
    terraform destroy -auto-approve

fmt:
    terraform fmt

validate:
    terraform validate

.PHONY: init plan apply destroy fmt validate